[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.app"

[deploy]
startCommand = "bun run --silent start -- -H 0.0.0.0 -p $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
